# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e5910a4e533ed8f9c93ba67b0b40a11b0cce83f4cf9ca55455e45c3256a1853efd1f9514ce49b87ea5917fa58099973da09adf8ac5414d2da831b6bcf1c7c73

test:
  secret_key_base: 37629dddb3fb51c7df34aac2378a672f49ed5f9d94e3655511cd4c287ff714d08f52b29e7ba30ba365edcc7a20b43e5d61c4c9e9261634288bc36697f7530e1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
